apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Storage, Compute
    datasuit: Develop, Analysis, Governance
    icon: https://hive.apache.org/favicon.ico
  name: hive-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HiveMetastore is the Schema for the hivemetastores API
      displayName: Hive Metastore
      kind: HiveMetastore
      name: hivemetastores.stack.zncdata.dev
      version: v1alpha1
  description: hive for operator
  displayName: hive-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - hive
  - metastore
  links:
  - name: Hive Operator
    url: https://github.com/zncdata-labs/hive-operator
  - name: Apache Hive
    url: https://hive.apache.org/
  maturity: alpha
  provider:
    name: zncdata-labs
    url: https://github.com/zncdata-labs
  version: 0.0.0
